#!/bin/bash

# ASCII Art
ascii_art=$(cat << "EOF"

 _   _  ___ _____    ___   ____  __   __
| \ | |/ _ \_   _|  / _ \ |  _ \ \ \ / /
|  \| | | | || |   | | | || |_) | \ V / 
| |\  | |_| || |   | |_| ||  __/   | |  
\_| \_/\___/ |_|    \___/ |_|      |_|  

             NOT APS XD

EOF
)

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Clear screen
clear

# Check if run as root
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Please run this script as root.${NC}"
  exit 1
fi

echo -e "${CYAN}$ascii_art${NC}"

echo -e "${YELLOW}* Installing Dependencies${NC}"
sudo apt update
sudo apt install -y curl software-properties-common git
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt install -y nodejs

echo -e "${GREEN}* Installed Dependencies${NC}"
echo -e "${YELLOW}* Cloning Files${NC}"

git clone https://github.com/draco-labes/draco-daemon
mv draco-daemon node
cd node
npm install

echo -e "${YELLOW}* Paste your configuration before proceeding.${NC}"
echo -e "${GREEN}* Starting the bot...${NC}"

node .
