#!/bin/bash

# ASCII Art
ascii_art="


 _   _       _      ___             __   _______ 
| \ | |     | |    / _ \            \ \ / /  _  \\
|  \| | ___ | |_  / /_\ \_ __  ___   \ V /| | | |
| . \` |/ _ \| __| |  _  | '_ \/ __|  /   \| | | |
| |\  | (_) | |_  | | | | |_) \__ \ / /^\ \ |/ / 
\_| \_/\___/ \__| \_| |_/ .__/|___/ \/   \/___/  
                        | |                      
                        |_|                      

                                 
"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Helper function
echo_message() {
  echo -e "${GREEN}$1${NC}"
}

# Clear the screen
clear

# Check if the script is run as root
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Please run this script as root.${NC}"
  exit 1
fi

echo -e "${CYAN}$ascii_art${NC}"

echo_message "* Installing Dependencies"

# Update package list and install dependencies
apt update
apt install -y curl software-properties-common
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt install -y nodejs git

echo_message "* Installed Dependencies"
echo_message "* Installing Files"

# Create directory, clone repository, and install files
git clone https://github.com/draco-labes/draco-daemon && mv draco-daemon node && cd node && npm install

echo -e "${YELLOW}* Paste your configuration before starting.${NC}"
echo_message "* Starting bot..."
node .
